# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translSens', models.CharField(choices=[('EN-FR', 'EN-FR'), ('FR-EN', 'FR-EN')], default='EN-FR', max_length=5)),
                ('termSource', models.CharField(max_length=20, null=True)),
                ('termTarget', models.CharField(max_length=20, null=True)),
                ('corpus', models.CharField(choices=[('Vulcanologie', 'Vulcanologie'), ('Diab\xe8te', 'Diab\xe8te'), ('Cancer du sein', 'Cancer du sein')], default='Vulcanologie', max_length=5)),
            ],
        ),
    ]
