# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KRCTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRCdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceSource', models.CharField(max_length=500)),
                ('sentenceTarget', models.CharField(max_length=500)),
                ('collocationSource', models.CharField(max_length=20, null=True)),
                ('collocationTarget', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='KRC',
            new_name='KRCrequest',
        ),
        migrations.AddField(
            model_name='krcdata',
            name='krcrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRCTool.KRCrequest'),
        ),
    ]
