# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRCTool', '0004_krcdata_collocationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='krcrequest',
            name='valide',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
