# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRCTool', '0005_krcrequest_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tttermSource', models.CharField(max_length=20, null=True)),
                ('transCandidate', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='krcrequest',
            name='valide',
        ),
    ]
